---
- name: loxilb
  hosts: "{{ lb }}"
  gather_facts: no
  become: yes
  become_user: root
  vars:
    root_dir: /data0
    docker_dir: "{{ root_dir }}/docker"
    id: 0
    self_ip: ""
    peer_ip: ""

  tasks:
  - name: install docker-ce repo
    shell: dnf config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  - name: install docker-ce
    shell: dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  - name: config docker dameon
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
            "data-root": "{{ docker_dir }}",
            "bip": "10.247.0.1/16"
        }
      mode: "0644"
  - name: start docker
    shell: systemctl start docker && systemctl enable docker

  - name: start loxilb
    shell: docker run --restart unless-stopped -u root --cap-add SYS_ADMIN --network host --privileged -dit -v /etc/localtime:/etc/localtime:ro -v /dev/log:/dev/log --name loxilb ghcr.io/loxilb-io/loxilb:v0.9.8.3 -p --self={{ id }} --cluster={{ peer_ip }} --ka={{ peer_ip }}:{{ self_ip }}
  - name: check loxilb
    shell: ps auxww | grep loxilb | grep -v grep
    register: result
  - debug: var=result.stdout

  - name: add alias loxicmd
    shell: |
      echo "alias loxicmd='docker exec loxilb loxicmd'" >> /root/.bashrc
      echo "alias gobgp='docker exec loxilb gobgp'" >> /root/.bashrc
